### ISSUE TITLE
Mac M1: Unable to run on Simulator

### ISSUE THREAD

**Issue by ppave** [Mattijah/QKMRZScanner#32] opened 2023-03-16 16:58 UTC
<img width="659" alt="image" src="https://user-images.githubusercontent.com/33399159/225694930-f3c12cca-0be8-4bd3-a560-40977262d511.png">

Hello, I am facing this issue [https://github.com/SwiftyTesseract/SwiftyTesseract/tree/support/3.x.x#note-on-cocoapods](https://github.com/SwiftyTesseract/SwiftyTesseract/tree/support/3.x.x#note-on-cocoapods)  on M1 trying to launch the app on Simulator.

Thanks in advance for any advices.

**Comment by Mattijah** [comment] 2023-03-16 21:45
Is this issue related to `QKMRZScanner` and the linked `SwiftyTesseract` or `QKMRZParser` as shown on the screenshot?
I'm confused. Since I'm also not using M1, I'm unable to reproduce the issue.

**Comment by ppave** [comment] 2023-03-16 22:12
Sorry for confusion. The problem is that QKMRZScanner triggers the above error when I try to run the app on Simulator.
But seems like this issue is similar to this one  https://github.com/SwiftyTesseract/SwiftyTesseract/tree/support/3.x.x#note-on-cocoapods. 
Also, I tried different pods settings and in some cases I see this error https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator caused by QKMRZScanner.
Let me know if you need more information.
I run on M1. My colleague has Intel-based mac and he doesn't have this problem.

**Comment by Mattijah** [comment] 2023-03-16 22:26
I think the problem is that the particular version of the `SwiftyTesseract` does not support M1. I am unable to upgrade it at this moment as I would also have to drop support for Cocoapods (newer version of the `SwiftyTesseract` doesn't support it).

For now, I'd probably suggest you to looking into some forks of `QKMRZScanner ` that are already using `SwiftyTesseract` v4. I might create another branch with this version and SPM support only as well. 

I can't really help you further as this is a 3rd party library I have no control over.

**Comment by ppave** [comment] 2023-03-16 22:36
Thank you.

**Comment by Mattijah** [comment] 2023-03-26 23:59
There is a now a new [branch](https://github.com/Mattijah/QKMRZScanner/tree/master-spm) with a better M1 support as it uses `SwiftyTesseract` v4. This version however only supports SPM. I'm closing this issue as it can't be resolved any further.

**Closed as completed by Mattijah** 2023-03-26 23:59 UTC

**Comment by ppave** [comment] 2023-03-27 08:17
Hi @Mattijah 
Just checked it and it's working, thank you for your work.
