### ISSUE TITLE
Error: LSTM requested, but not present

### ISSUE THREAD

**Issue by mehdi-S** [Mattijah/QKMRZScanner#9] opened 2020-03-24 09:12 UTC
Hi, trying to use your project everything setup fine and fast, except when i'm trying to scan something it didn't call the delegate.

when looking at the console, at launch I can see this error occuring everytime : 

`Error: LSTM requested, but not present!! Loading tesseract.`

i've tried to create reference to tessdata file in the main project folder with no success

**Comment by Mattijah** [comment] 2020-03-25 14:33
Hi,

That's weird. I will have a look at it. What iOS/Swift/Xcode version are you using?

**Comment by mehdi-S** [comment] 2020-03-25 17:39
i'm using xcode 11.4, swift 5, ios 13.4

**Comment by Mattijah** [comment] 2020-03-28 16:53
@mehdi-S So I don't have the latest Xcode, but I was able to reproduce the error with Xcode 11.3.1 and iOS 13.3.1. More importantly, the scanning was working correctly despite this error shown in the console. Are you sure your delegate is setup correctly...?

**Comment by mehdi-S** [comment] 2020-03-30 08:20
delegate setup correctly, yes indeed, scan is working as intended
I wanted to point this to you as it surely means something's wrong and that I wasn't sure what

**Comment by sonmezvolkan** [comment] 2020-04-01 10:21
Same problem, because  there is no tessdata

**Comment by Mattijah** [comment] 2020-04-01 12:54
`tessdata` is here https://github.com/Mattijah/QKMRZScanner/tree/master/QKMRZScanner/Supporting%20Files/tessdata and it is also being used, however not with the chosen LSTM engine, but default tesseract (hence the error). I need to update the traineddata to support the LSTM. **Everything should work just fine in regards to scanning and performance though.**

**Comment by SkyptoOfficial** [comment] 2020-04-16 02:15
im faced with the same error

**Comment by ivanalumP** [comment] 2020-07-07 13:31
facing same error with xcode 11.5 with correct delegate

**Comment by Mattijah** [comment] 2020-10-04 21:03
Resolved in [`v2.2.0`](https://github.com/Mattijah/QKMRZScanner/releases/tag/v2.2.0)

**Closed as completed by Mattijah** 2020-10-04 21:03 UTC
