### ISSUE TITLE
Designable error in storyboard

### ISSUE THREAD

**Issue by LaurentDaudelin** [Mattijah/QKMRZScanner#18] opened 2020-12-18 21:12 UTC
Not sure if I'm doing something wrong. I created a brand new project in Xcode 12.2. Added a view to my initial view controller. Switched the class to QKMRZScannerView and I now have a **Designable** error.

Here is my pod environment:

```
### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '14'

target 'Testing QKMRZScannerView' do
  pod 'QKMRZScanner'
end
```

```

**Comment by Mattijah** [comment] 2022-04-02 22:29
Hey @LaurentDaudelin pretty late reply from me, but nevertheless I am not able to reproduce your issue. Running currently: Xcode 13.3 and CocoaPods 1.11.2. It's been working fine before too.

I'm closing this issue, but if you have any more questions/comments feel free to post them. Thanks!

**Closed as completed by Mattijah** 2022-04-02 22:29 UTC
