### ISSUE TITLE
Memory is increased continuously

### ISSUE THREAD

**Issue by jigs4444** [Mattijah/QKMRZScanner#8] opened 2020-02-10 12:11 UTC
Hi i have implemented the library for scanning passport. When i am scanning the passport continuously , i see memory is increased and it's not decreasing.

[
![Screenshot 2020-02-10 at 4 23 28 PM](https://user-images.githubusercontent.com/12757616/74148877-79906680-4c2c-11ea-8dc9-7e548f2d788a.png)
](url)

Any way to deal with this?

**Comment by Mattijah** [comment] 2020-02-10 12:19
Weird. Could you please expand on what you mean by _"scanning  continuously"_? Do you make multiple successful scans or you just keep scanning and the memory increases as time passes..? Also, what iOS version are you on?

**Comment by jigs4444** [comment] 2020-02-10 12:21
i keep scanning even though i get success or failure . Due to requirements i had to comment the code for stopScanning method. I need to detect password only if i click capture button from my custom UI.

**Comment by Mattijah** [comment] 2020-02-10 12:29
I see. I will need to look into this. I remember that scanning as it is, has been tested and there weren't any memory problems. I may also add an option that would allow you to deactivate this auto-stop feature.

**Comment by jigs4444** [comment] 2020-02-10 12:43
Exactly . I want to change border color of cutview if MRZ is valid else normal color. And user can only take picture via button if border is showing valid MRZ code

**Comment by Mattijah** [comment] 2020-02-10 12:56
Why do you need to involve user in the process that can be automated?

**Comment by jigs4444** [comment] 2020-02-10 14:03
Requirements are like that only so i have to do it accordingly

**Comment by Mattijah** [comment] 2020-02-13 02:54
Seems like this memory leak is caused by one of our dependencies. [SwiftyTesseract](https://github.com/SwiftyTesseract/SwiftyTesseract) to be more precise.

https://github.com/SwiftyTesseract/SwiftyTesseract/issues/50

**Comment by Mattijah** [comment] 2020-10-04 21:04
Resolved in [`v2.2.0`](https://github.com/Mattijah/QKMRZScanner/releases/tag/v2.2.0)

**Closed as completed by Mattijah** 2020-10-04 21:04 UTC
