### ISSUE TITLE
Unable to read ID card with MRZ of 3 lines

### ISSUE THREAD

**Issue by faris-mobile89** [Mattijah/QKMRZScanner#1] opened 2019-03-13 06:13 UTC
I'm unable to read an ID of 3 lines. Could you please support us or give me an idea to do this. Thanks

**Comment by Mattijah** [comment] 2019-03-13 10:09
The module does support IDs with 3 lines of MRZ (td1 format). You should have no problem with that. Could you please provide some more details? What kind of ID are you trying to scan?

**Comment by faris-mobile89** [comment] 2019-03-13 10:11
Could you please try scan below image ?

![IMG_4152](https://user-images.githubusercontent.com/5647039/54270912-dfe2b400-4599-11e9-9028-36f0716742e3.jpg)

**Comment by Mattijah** [comment] 2019-03-13 15:20
Ah, I see. I think the problem is the image in the middle, behind the text. I need to investigate it more, but I feel like the module can't probably detect the text clearly.

Try for instance this ID. It should work without any issue and it uses the exactly same format.
![id card sample 4 copy](https://user-images.githubusercontent.com/3887042/54290820-ee39cb80-45ab-11e9-8c5c-f6289fc530a7.jpg)

**Comment by faris-mobile89** [comment] 2019-03-13 15:23
Thanks for the response, Yes might be the camera logo inside MRZ text. Do you have any idea how to bypass this issue? I will be thankful if you support me :)

**Comment by Mattijah** [comment] 2019-03-13 15:29
This section here (image processing: https://github.com/Mattijah/QKMRZScanner/blob/master/QKMRZScanner/QKMRZScannerView.swift#L232-L273) need to be changed (improved) so the camera image will get removed (filtered out) and only the text will stay in.

**Comment by Mattijah** [comment] 2019-07-09 23:07
Issue resolved in [v2.1.0](https://github.com/Mattijah/QKMRZScanner/releases/tag/v2.1.0)

**Closed as completed** 2019-07-10 17:18 UTC
